version: '3.9'

services:
  rakuten_api:
    build:
      context: ./backend-app/
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      rakuten_network:
        ipv4_address: 172.23.0.3
  postgres:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
    - .env
    ports:
    - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      rakuten_network:
        ipv4_address: 172.23.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rakuten_db"]  # Health check command
      interval: 10s 
      retries: 20 #change this from 5 to 20 to check if this is the issue for the tests
      start_period: 10s
      timeout: 5s

networks:
  rakuten_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
